apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lounas-ingress
spec:
  rules:
    - http:
        paths:
          - path: /lounas
            backend:
              serviceName: lounas
              servicePort: 8000
